### ISSUE TITLE
Installation via composer global

### ISSUE THREAD

**Issue by halkyon** [silverstripe/sspak#21]
Would be awesome if you could install sspak via composer:

`composer global require "silverstripe/sspak"`

That would install sspak into into `~/.composer/vendor/bin/`, just like how you'd install PHPUnit globally for a user.

**Comment by robbieaverill** [comment]
This package needs to be submitted to Packagist before it can be installed without a VCS repo - would someone mind doing that? cc @sminnee

**Comment by dhensby** [comment]
done: https://packagist.org/packages/silverstripe/sspak

**Comment by robbieaverill** [comment]
Thanks :-)
