### ISSUE TITLE
SSPAK is using double the diskspace on save

### ISSUE THREAD

**Issue by stojg** [silverstripe/sspak#27]
When creating new sspak it seems to first using double the space 

This is an example during a run from the temporary files in /tmp.

```
-rw-r--r--  1 www-data www-data 6.6G Jun 30 12:37 sspak-content-723399
-rw-------  1 www-data www-data 6.6G Jun 30 12:39 phpnqTfmI
```
the `phpnqTfmI` seems to be a php tempfile() that is used for some operation instead of the original `sspak-content-723399` file

**Comment by halkyon** [comment]
Not much we can do about this unfortunately. Seems to be an internal thing of Phar when you call `PharData::addFile()`, and streaming the file in doesn't seem to be supported.
