### ISSUE TITLE
Error - Can't process database type 'MySQLPDODatabase'

### ISSUE THREAD

**Issue by robbyahn** [silverstripe/sspak#33]
When I run the following command

$> sspak save --db /var/www/html/mysite local-test2.sspak

then return the following
Can't process database type 'MySQLPDODatabase'

**Comment by tractorcow** [comment]
Need to add a new method to support PDO databases.

It can probably just call putdb_MySQLDatabase

**Comment by camfindlay** [comment]
+1

**Comment by camfindlay** [comment]
+1 again

**Comment by dhensby** [comment]
Created  PR for it

**Comment by tractorcow** [comment]
Thanks @dhensby

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/sspak/pull/34

**Comment by madmatt** [comment]
That fixes it in the code, but the installer still pulls the wrong version down, because the builder hasn't been run. I'll try and sort that now.

**Comment by tractorcow** [comment]
Thanks.

**Comment by madmatt** [comment]
PR raised here: https://github.com/silverstripe/sspak/pull/35
