### ISSUE TITLE
Fix install

### ISSUE THREAD

**Issue by sminnee** [silverstripe/sspak#4]
The install script needs a few tweaks:
- It should run `composer install` if checked out from git.
- It should check out the specific sha if the sha is different from the branch.
- It should run `dev/build`, using the sudo user.

The install script in self-extracting archives should also assume that the first argument is the current script, and limit actions to `load` and `install`.

**Comment by marksy** [comment]
plus 1 from mee

**Comment by sminnee** [comment]
To be honest, I think that this use-case for sspak is probably not recommended. What are you trying to do? Perhaps there's a better approach...

**Comment by marksy** [comment]
Trying to migrate the db & assets from our staging server to a local docker instance.

I've extracted the staging .sspak but when i try to `sspak load site.sspak ./` in the docker instance it fails with mysql not found. Perhaps i need to set env vars

**Comment by sminnee** [comment]
It requires the mysql client binary to be available; perhaps that's not on your docker? In any case, this github issue related to something else; I'm going to close it as wontfix.

**Comment by sminnee** [comment]
Also y'all should sign up to https://www.silverstripe.org/community/slack-signup/ - it's a good place for tech support.

**Comment by marksy** [comment]
Cool ty :)
