### ISSUE TITLE
Add --symlink option to install

### ISSUE THREAD

**Issue by sminnee** [silverstripe/sspak#5]
For example:

    sspak install my.sspak /sites/mysite/releases/123 --symlink=/sites/mysite/www

This would install to `/sites/mysite/releases/123`, run the post-installation script, and then create `/sites/mysite/www` as a symlink pointing to `/sites/mysite/releases/123`.

**Comment by DarrenInwood** [comment]
+1 for this.

**Comment by dhensby** [comment]
Sounds like a good idea :)

**Comment by silverstripesk** [comment]
I don't like the idea of making sspak a deployment tool. Keep sspak as simple as possible, we can implement it easily to deployment strategy which suits our (custom) needs.

**Comment by sminnee** [comment]
Yeah it made more sense a few years ago; closing this.

**Comment by silverstripesk** [comment]
This is similar to #7. This should be closed too.
