### ISSUE TITLE
sspak load destroys assets symlink

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/sspak#62]
I deploy a capistrano style with [deployer php](https://deployer.org/), which symlinks `assets` in each release.

Using `sspak load my.sspak /path/to/current` destroys the assets symlink in `current` and generates an assets directory with the new content - which is lost in the next release.

See https://github.com/silverstripe/sspak/blob/d697d767758d713952a4e0b21c0cd3b1088462e2/src/Webroot.php#L138-L157 where that happens.

**Comment by andrewandante** [comment]
What does `assets` symlink to? I wonder if we can detect that it's a link, and act accordingly. Probably recreate the symlink is the best bet I think, but would need to do some testing.

**Comment by wernerkrauss** [comment]
My structure is like:

_/path/to/public_html/_: root of whole installation, contains _ss_environment.php
_/path/to/public_html/shared_:  contains shared stuff
_/path/to/public_html/shared/assets_:  assets dir
_/path/to/public_html/releases/_:  releases
_/path/to/public_html/releases/1234_:  a release
_/path/to/public_html/releases/1234/assets_:  symlink to /path/to/public_html/shared/assets
_/path/to/public_html/current_:  symlink to latest release; apache webroot

one possible solution instead of renaming old assets and deleting them later would be to clear it and extract into it using tar's `--strip 1` parameter. Or just the current logic in the _shared/_ folder instead the webroot.

**Comment by andrewandante** [comment]
@wernerkrauss could you give this one a bash? I've tried it out on my Bash-on-Windows env, but it'd be great if you could test as well.

**Comment by NZI** [comment]
Confirmed here

**Comment by andrewandante** [comment]
@NZI could you test using my fork? The more positive results the better :)

Then maybe I'll get @dhensby to merge it for ~me~ us 😄
