### ISSUE TITLE
sspak throwing error on mysqldump step of create archive

### ISSUE THREAD

**Issue by caniwi** [silverstripe/sspak#78]
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces

This is a result of the breaking change introduced in MySQL minor updates 5.7.31 and 8.2.21 in 2020/07 https://dev.mysql.com/doc/relnotes/mysql/5.7/ ... 31.html#mysqld-5-7-31-security . Access to the PROCESS privilege is a security issue.

Having looked at the sspak code, it should be modified to have the --no-tablespaces option added to the mysqldump command in the getdb_MySQLDatabase function.

The sspak code still produces the dump, so maybe it should be a Warning rather than an Erro.

**Comment by caniwi** [comment]
Pull request # 79.

**Comment by lerni** [comment]
^^ update link: https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-31.html
