### ISSUE TITLE
Unknown table 'COLUMN_STATISTICS' in information_schema (1109) error

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/sspak#81]
Getting an error when running sspak with MySQL 5.7.

```
Couldn't execute 'SELECT COLUMN_NAME, JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')
FROM information_schema.COLUMN_STATISTICS WHERE SCHEMA_NAME = 'xxxxxxx' AND
TABLE_NAME = 'Answer';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
```

Might be a specific db setting, but passing in `--column-statistics=0` to mysqldump fixes the issue. Will provide a PR.

**Comment by michalkleiner** [comment]
As a workaround we're using a proxy script adding these params, with the same name as the mysqldump binary, in a path that takes priority when searching for the executable. Works ok, so the addition should be ok, too.

```
#!/bin/sh

/usr/bin/mysqldump --no-tablespaces --column-statistics=0 $@
```

**Comment by emteknetnz** [comment]
@michalkleiner is it the same issue as this? https://serverfault.com/a/912677

i.e. you're using a mysql 8 client and accessing a mysql 5.7 database?

**Comment by michalkleiner** [comment]
Highly likely, @emteknetnz. We don't have access to MySQL settings to change the default in its config neither can install/choose the mysqldump binary version, it's whatever comes with the container (SiteHost Cloud Containers).

A relevant point would be to see what the presence of the switch does when passed to a 5.7 mysqldump binary.

**Comment by emteknetnz** [comment]
Closing issue as linked PR was merged
