### ISSUE TITLE
sspak save bails with mysqldump: unknown variable 'column-statistics=0'

### ISSUE THREAD

**Issue by bumbus** [silverstripe/sspak#90]
It looks like this flag was added to mysqldump with this commit:
https://github.com/silverstripe/sspak/commit/36add95cfd281a4318c77aa551114dbae6dbb34a

However, it looks like this causes an error while dumping the DB for some versions, e.g.:

mysqldump  Ver 10.19 Distrib 10.3.35-MariaDB, for debian-linux-gnu (x86_64)
mysql  Ver 15.1 Distrib 10.3.35-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Maybe it might help to expose this flag to the sspak command itself, so that the user can decide which mysql dump flags to use?

## Acceptance Criteria
- [x] This has been tested with MySQL 5, 8 and the most recent version of Maria DB
- [ ] Fix is made available in a patch release.
- [x] Validate that generated SSPAK files can be restored on our platforms

### PRs
- [ ] https://github.com/silverstripe/sspak/pull/91

**Comment by emteknetnz** [comment]
PR https://github.com/silverstripe/sspak/pull/91

**Comment by LoveDuckie** [comment]
Also encountering this problem with MariaDB 10.5

**Comment by sabina-talipova** [comment]
PR has been tested with MySQL 5.7.4 / 8.0.31, MariaDB 10.9.3.
Issue was solved.
